# Generated by Django 4.0.3 on 2022-04-06 08:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='post_date',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='post',
            name='post_text',
            field=models.TextField(blank=True),
        ),
    ]
